// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Span struct {
	ID            int64      `json:"id"`
	TraceRowid    *int64     `json:"trace_rowid"`
	SpanID        string     `json:"span_id"`
	ParentSpanID  *string    `json:"parent_span_id"`
	Name          string     `json:"name"`
	SpanKind      *string    `json:"span_kind"`
	StartTime     *time.Time `json:"start_time"`
	EndTime       *time.Time `json:"end_time"`
	Attributes    []byte     `json:"attributes"`
	Events        []byte     `json:"events"`
	InputTokens   *int64     `json:"input_tokens"`
	OutputTokens  *int64     `json:"output_tokens"`
	StatusCode    *string    `json:"status_code"`
	StatusMessage *string    `json:"status_message"`
	CreatedAt     *time.Time `json:"created_at"`
}

type ToolCallLog struct {
	ID            int64      `json:"id"`
	Timestamp     *time.Time `json:"timestamp"`
	TraceID       string     `json:"trace_id"`
	SessionID     *string    `json:"session_id"`
	ToolName      string     `json:"tool_name"`
	ToolArguments *string    `json:"tool_arguments"`
	ApiType       *string    `json:"api_type"`
	WasBlocked    *bool      `json:"was_blocked"`
	BlockedByRule *string    `json:"blocked_by_rule"`
	Model         *string    `json:"model"`
	Layer         *string    `json:"layer"`
	Protocol      *string    `json:"protocol"`
	Direction     *string    `json:"direction"`
	Method        *string    `json:"method"`
	BlockType     *string    `json:"block_type"`
}

type Trace struct {
	ID        int64      `json:"id"`
	TraceID   string     `json:"trace_id"`
	SessionID *string    `json:"session_id"`
	StartTime *time.Time `json:"start_time"`
	EndTime   *time.Time `json:"end_time"`
	Metadata  []byte     `json:"metadata"`
	CreatedAt *time.Time `json:"created_at"`
}
