// gen-ffi-schema extracts the stats keys from eventlog.Metrics.GetStats()
// and generates a Rust constant array so that Rust integration tests can
// detect FFI JSON schema mismatches at build time.
//
// Usage:
//
//	go run ./cmd/gen-ffi-schema -out ../../src-tauri/src/ffi_schema.rs
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/BakeLens/crust/internal/eventlog"
)

func main() {
	out := flag.String("out", "../../src-tauri/src/ffi_schema.rs", "output file path")
	flag.Parse()

	// Call GetStats on a zero-value Metrics to extract all map keys.
	var m eventlog.Metrics
	stats := m.GetStats()

	keys := make([]string, 0, len(stats))
	for k := range stats {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("// Code generated by gen-ffi-schema. DO NOT EDIT.\n")
	b.WriteString("pub const EXPECTED_STATS_KEYS: &[&str] = &[\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "    %q,\n", k)
	}
	b.WriteString("];\n")

	if err := os.WriteFile(*out, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-ffi-schema: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("gen-ffi-schema: wrote %d keys to %s\n", len(keys), *out)
}
